### ISSUE TITLE
No modelApiKey in response

### ISSUE THREAD

**Issue by timchesney** [ColinDorr/datocms-plugin-better-linking#8]
I might be missing something here, and apologies if so, but when I use the 'record' option to add a link, there is no modelApiKey data returned in the response which, as far as I'm aware, makes it impossible to resolve the link if you have more than one record type as there isn't a way to know which url structure to use.

**Comment by ghisleouf** [comment]
Hi here!
+1 on this one ... it makes the plugin very limited if the modelApiKey is not available for me, for the exact same reason.

**Comment by olivierbossel** [comment]
Hi!
+1
Thanks for the work done!

**Comment by ColinDorr** [comment]
@timchesney @ghisleouf @olivierbossel Thanks so much for your feedback!

I’m currently working to incorporate this functionality. Below, I’ve provided examples of the new data objects. While `Url`, `Email`, and `Telephone` remain unchanged, the `Record`, `Asset`, and `Formatted` objects now include additional fields. These enhancements are intended to address your feedback by providing more context on the selected content source.

Could you please review the structures below and let me know if this setup sufficiently supports your requirements and your development needs. 

### Record:
```
"record": {
	"id": "181050790",
	"title": "Privacy Policy",
	"cms_url": "https://marketing-test-environment.admin.datocms.com/editor/item_types/2124827/items/181050790/edit",
	"slug": "privacy-policy",
	"status": "published",
	"url": "privacy-policy",
	"modelDate": {
	"id": "2124827",
	"api_key": "legal_page",
	"label": "🏛️ Legal Page",
	"type": "item_type"
	},
	"modelApiKey": "legal_page"
},
```

### Asset:
```
"asset": {
	"id": "68715688",
	"title": "minimalistgridposts.png",
	"alt": "minimalistgridposts.png",
	"cms_url": "https://www.datocms-assets.com/138675/1694686221-minimalistgridposts.png",
	"status": "published",
	"url": "https://www.datocms-assets.com/138675/1694686221-minimalistgridposts.png"
},
```

### URL:
```
"url": {
	"title": "URL",
	"url": "https://wwww.text.com"
},
```

### Telephone:
```
"tel": {
	"title": "Telephone number",
	"url": "tel:0612345678"
},
```

Email:
```
"email": {
	"title": "Email address",
	"url": "mailto:user@mail.com"
},
```

### Formatted
```
"formatted": {
	"isValid": true,
	"type": "asset",
	"modelApiKey": "legal_page",
	"text": "Privacy",
	"ariaLabel": "Bekijk onze privacy policy",
	"url": "https://www.datocms-assets.com/138675/1694686221-minimalistgridposts.png",
	"target": "_blank",
	"class": null
},
```

**Comment by timchesney** [comment]
Thanks @ColinDorr ! That looks great to me and would definitely fit my purposes. 
I can see myself using this a lot as I currently always make a 'link' block that I reuse in buttons and navigations etc but your plugin is much simpler for the editor and easier to query too which is awesome. Thanks for making it!

**Comment by ColinDorr** [comment]
Hey @timchesney,

The new version is almost ready, and things are shaping up nicely. I’m down to fixing a few minor bugs and testing out some edge cases to make sure everything runs smoothly.

If all goes well, I should be able to roll it out over the weekend.

**Comment by ColinDorr** [comment]
Hi @timchesney, @ghisleouf, @olivierbossel,

I’m pleased to announce that the new version has been released!

To see the new changes, you may need to resave the relevant field in the record.

I hope these updates enhance your development experience. If you have any questions or need further assistance, please don’t hesitate to open an issue, and I’ll do my best to help you.

**Comment by ColinDorr** [comment]
Hi @timchesney, @ghisleouf, @olivierbossel,

I’m pleased to announce that the new version has been released!

To see the new changes, you may need to resave the relevant field in the record.

I hope these updates enhance your development experience. If you have any questions or need further assistance, please don’t hesitate to open an issue, and I’ll do my best to help you.

**Comment by devenini** [comment]
Hey @ColinDorr — thank you for this plugin!  

However, I’m encountering the issue where `modelApiKey` is not included in the response of a `"record"` link. I am using the version **0.2.2** of the plugin.

Here’s an example of `formatted` object of the response:

```
formatted: {
  isValid: true,
  type: 'record',
  text: "Lorem Ipsum: The Future of Placeholder Content",
  ariaLabel: "Lorem Ipsum: The Future of Placeholder Content",
  url: 'lorem-ipsum-the-future-of-placeholder-content',
  target: '_self',
  class: null
}
```

For context I am using the plugin inside a block (multiples). The `modelApiKey` is also missing in the `record` part of the response

Ty!

**Comment by devenini** [comment]
Hey! It looks like this bug was reintroduced in `v0.2.7`. The `modelApiKey` field is now missing from the formatted response for record links.

Here's what I'm seeing:

```
  "formatted": {
    "isValid": true,
    "type": "record",
    "text": "Cooler Rental",
    "ariaLabel": "Cooler Rental",
    "url": "cooler-rental",
    "target": "_self",
    "class": null
  }
```

@arcataroger do you think #17 could have reintroduced this bug?

**Comment by arcataroger** [comment]
We'll take a look, @devenini! Sorry about that.
